# Generated by Django 4.0.5 on 2022-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_lc_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='achievement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
