# Generated by Django 4.0.5 on 2022-11-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_about_achievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workedclub',
            old_name='icons',
            new_name='image',
        ),
    ]
