# Generated by Django 4.0.5 on 2022-12-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_lc_certificate_rename_memorablemoment_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactme',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
