# Generated by Django 4.0.5 on 2022-12-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contactme_instagram_link_contactme_linkedin_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactme',
            name='additional',
        ),
    ]
