# Generated by Django 4.0.5 on 2022-12-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_contactme_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
